-- Pairing codes (short-lived) generated by web app, redeemed by extension
CREATE TABLE public.extension_pair_codes (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  code TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  redeemed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_extension_pair_codes_user ON public.extension_pair_codes(user_id);
CREATE INDEX idx_extension_pair_codes_code ON public.extension_pair_codes(code);

ALTER TABLE public.extension_pair_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own pair codes"
  ON public.extension_pair_codes FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own pair codes"
  ON public.extension_pair_codes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Long-lived extension tokens issued after redemption
CREATE TABLE public.extension_tokens (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  token TEXT NOT NULL UNIQUE,
  device_label TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ
);
CREATE INDEX idx_extension_tokens_user ON public.extension_tokens(user_id);
CREATE INDEX idx_extension_tokens_token ON public.extension_tokens(token);

ALTER TABLE public.extension_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own tokens"
  ON public.extension_tokens FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own tokens"
  ON public.extension_tokens FOR UPDATE
  USING (auth.uid() = user_id);
